name: Lua Lint

on:
  push:
    branches:
    - master
    paths:
      - "lua/**"
      - "init.lua"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Tools
      run: |
        wget -c "https://github.com/Kampfkarren/selene/releases/download/0.15.0/selene-0.15.0-linux.zip" -O ./selene.zip
        unzip ./selene.zip
        chmod +x ./selene
    - name: Run lint
      shell: bash
      run: ./selene --config ./fixtures/lint/config.toml lua
