name: Config Test

on:
  push:
    branches:
    - master
    paths:
      - "lua/**"
      - "init.lua"

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: alpine:edge

    steps:
    - name: Install Neovim
      shell: sh
      run: apk add git neovim ripgrep alpine-sdk --update
    - name: Clone Configuration
      run: git clone https://github.com/Avimitin/nvim $HOME/.config/nvim
    - name: Test packer complie
      run: |
        LOG_FILE=$(mktemp)
        nvim --headless -c "au VimEnter * quitall" > $LOG_FILE 2>&1
        if rg -qS "err" $LOG_FILE; then cat $LOG_FILE; false; fi
